version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_custom.conf:/etc/postgresql/pg_custom.conf   # Mount the custom config
    command: ["postgres", "-c", "config_file=/etc/postgresql/pg_custom.conf"]

volumes:
  postgres_data: